services:
  backend:
    build:
      context: ./services/backend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./services/backend:/app
    #   - /app/node_modules
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/app_db
      - JWT_SECRET=your-super-secret-key-that-is-long-and-random
    # env_file:
    #   - ./services/backend/.env
    depends_on:
      - db
    # command: npm run dev

  frontend:
    build:
      context: ./services/frontend
    ports:
      - "80:80"
    volumes:
      - ./services/frontend/src:/app/src
      - ./services/frontend/public:/app/public
    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db

volumes:
  postgres_data:
